contentColumnType: string
fieldGroup: f9187653-3981-41ca-952e-68db965c7680
handle: introductionImage
instructions: ''
name: 'Introduction Image'
searchable: true
settings:
  allowedKinds: null
  defaultUploadLocationSource: 'volume:056e6fd0-f65b-4537-b4c0-ae47aa59c0c3' # Gallery
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  restrictFiles: ''
  selectionLabel: ''
  singleUploadLocationSource: 'volume:59809b76-067a-4c9c-a52d-27711ece3121' # Introduction
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: '1'
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
