dateModified: 1640207033
email:
  fromEmail: magnessjo@gmail.com
  fromName: 'Winston React'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    0cff2ec7-a499-406a-9426-f7231efa321e: About # About
    01d4cc27-6d10-46e5-a73f-5cc908f31e8a: About # About
    2ab75266-cf78-4f46-a731-596008b430da: 'Gallery Category' # Gallery Category
    4b26de30-3f80-4bc2-aa3e-59de9e4cd816: Text # Text
    7d892131-3b69-4410-a6cd-3a393b515df9: About # About
    29f883c0-10a9-4a64-b734-757d94c9bef7: 'Introduction Image' # Introduction Image
    056e6fd0-f65b-4537-b4c0-ae47aa59c0c3: Gallery # Gallery
    0708e7b4-6343-4456-a9f4-d4b1509091d7: 'Public Schema' # Public Schema
    789d0d3b-0908-4168-b2c8-63474ae11cb3: 'Introduction Summary' # Introduction Summary
    3794e699-591e-43a4-aad8-196fa9d7cdea: 'Gallery Summary' # Gallery Summary
    59809b76-067a-4c9c-a52d-27711ece3121: Introduction # Introduction
    a557434d-fe65-48cf-ba68-28a264823415: Image # Image
    bcb49428-6959-4bb9-a832-ce891bc103ed: Introduction # Introduction
    bf35d2c0-1479-4275-b658-e95cb14f9b3f: 'About Type' # About Type
plugins:
  redactor:
    enabled: '1'
    licenseKey: null
    schemaVersion: 2.3.0
    settings: null
system:
  edition: pro
  live: true
  name: 'Winston React'
  schemaVersion: 3.7.8
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: ''
  photoVolumeUid: null
  requireEmailVerification: true
